spring.application.name=unsaid-api
# ---- H2 FILE (persistent) ----
spring.datasource.url=jdbc:h2:file:./data/unsaid-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Keep tables as code changes
spring.jpa.hibernate.ddl-auto=update

# Optional: H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# (Optional) cleaner logs
spring.jpa.open-in-view=false
